export interface ArchitectureComponent {
  id: string;
  technologyId: string;
  name: string;
  purpose: string;
  reason: string;
  alternatives: string[]; // technology names, not ids - ready to display
  tradeoffs: string;
  failureBehavior: string;
  scalingStrategy: string;
  // Diagram grouping category. Optional - only set by the AI-driven generator;
  // the rule-based fallback doesn't group, and older saved designs won't have it.
  kind?: string;
}

export interface ArchitectureConnection {
  from: string; // component id
  to: string; // component id
  label?: string;
}

export interface FailureScenario {
  scenario: string;
  impact: string;
  mitigation: string;
  recovery: string;
}

export interface Bottleneck {
  component: string;
  reason: string;
  howToDetect: string;
  mitigation: string;
}

export interface TenXScaleAnalysis {
  fromScale: string;
  toScale: string;
  changes: string[];
}

export interface Architecture {
  components: ArchitectureComponent[];
  connections: ArchitectureConnection[];
  // Optional - only present when generated by the AI path.
  domain?: string;
  designRationale?: string[];
  failureScenarios?: FailureScenario[];
  bottlenecks?: Bottleneck[];
  tenXScale?: TenXScaleAnalysis;
}
