export interface ArchitectureComponent {
  id: string;
  technologyId: string;
  name: string;
  purpose: string;
  reason: string;
  alternatives: string[]; // technology names, not ids - ready to display
  tradeoffs: string;
  failureBehavior: string;
  scalingStrategy: string;
  // Diagram grouping category. Optional - only set by the AI-driven generator;
  // the rule-based fallback doesn't group, and older saved designs won't have it.
  kind?: string;
}

export interface ArchitectureConnection {
  from: string; // component id
  to: string; // component id
  label?: string;
}

export interface Architecture {
  components: ArchitectureComponent[];
  connections: ArchitectureConnection[];
  // Optional - only present when generated by the AI path.
  domain?: string;
  designRationale?: string[];
}
